### ISSUE TITLE
Add ssd1306_font

### ISSUE THREAD

**Issue by Nondzu** [tinygo-org/awesome-tinygo#2]
I have made this little library recently for the OLED display SSD1306. It will be very nice to see them on this list.
link to repo: github.com/Nondzu/ssd1306_font

PS. 
This list is really helpful ! 
I believe these repository will grow. Maybe it would be worth pinning them to the tinygo project somehow?

**Comment by soypat** [comment]
Would you mind making a pull request to add the library in its corresponding place?

**Comment by Nondzu** [comment]
@soypat sure here is https://github.com/soypat/awesome-tinygo/pull/3

**Comment by soypat** [comment]
Thank you for the contribution! :smile:
